modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/univrsal/JustEnoughButtons/issues" #optional
[[mods]] #mandatory
modId="justenoughbuttons" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Just Enough Buttons" #mandatory
logoFile="logo.png" #optional
credits="the Minecraft Forge team" #optional
authors="univrsal" #optional
description='''
Utility buttons for your inventory screen
'''