modLoader="javafml" #mandatory
loaderVersion="[14,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/univrsal/JustEnoughButtons/issues" #optional
[[mods]] #mandatory
modId="justenoughbuttons" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Just Enough Buttons" #mandatory
logoFile="logo.png" #optional
credits="the Minecraft Forge team" #optional
authors="univrsal" #optional
description='''
Utility buttons for your inventory screen
'''

[[dependencies.justenoughbuttons]]
    modId="forge" #mandatory
    mandatory=false #mandatory
    versionRange="[26.0.47,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"